"""empty message

Revision ID: f4dd95ac04a6
Revises: 
Create Date: 2020-07-20 15:08:38.721390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4dd95ac04a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('marketing', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['github'])
    op.create_unique_constraint(None, 'user', ['twitter'])
    op.create_unique_constraint(None, 'user', ['linkedin'])
    op.create_unique_constraint(None, 'user', ['social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'marketing')
    # ### end Alembic commands ###
